name: Deploy Nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
